version: "3.9"

services:
  django_api:
    build:
      context: .
      dockerfile: DjangoDockerfile
    image: django-api:latest
    container_name: django_api
#    environment:
#      - DB_HOST=postgres_db
#      - DB_NAME=test_api
#      - DB_USER=admin
#      - DB_PASS=admin
#      - DB_PORT=5432
    env_file:
      - django-api/.env
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: sh -c "chmod +x /app/scripts/migrate.sh && chmod +x /app/scripts/entrypoint.sh &&
             sh /app/scripts/migrate.sh && /app/scripts/entrypoint.sh"
#    volumes:
#      - staticfiles:/app/staticfiles/
#    volumes:
#      - ./django-api:/app
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:12-alpine
    restart: always
    command: -p 5430
    expose:
      - 5430
    ports:
      - "5430:5430"
#    environment:
#      - POSTGRES_DB=test_api
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
    env_file:
      - django-api/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis_db:
    image: redis:alpine
    restart: always
    expose:
      - 6388
    ports:
      - "6388:6388"
    volumes:
        - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6388

volumes:
  postgres_data:
  redis_data:
#  staticfiles:
#    external: true

