apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-api-deployment
  template:
    metadata:
      labels:
        app: django-api-deployment
    spec:
      containers:
        - name: django
          image: django-api
          env:
            - name: "PORT"
              value: 8080
          ports:
            - containerPorts: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: django-api-deployment

