---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: horizontal-pod-autoscaling
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: bhatraideb/flask-api:latest      # aputra/myapp-195:v2      # Need to change this Image
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 100m