---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: default
  name: reader-binding
roleRef:
  kind: ClusterRole
  name: reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: reader-group
    namespace: default
    apiGroup: rbac.authorization.k8s.io
